project_resources += files(
    'ICommand.vala',
    'IResultProvider.vala',
    'SearchResult.vala',
    'GnomeSearchProvider.vala',
    'AppsCmd.vala',
    'AppsCmdButton.vala',
    'ClipboardCmd.vala',
    'FilesCmd.vala',
    'HelpCmd.vala',
    'MathCmd.vala',
    'MathHistoryManager.vala',
    'SysInfoCmd.vala',
    'SysInfoItem.vala',
    'WeatherCmd.vala'
)