install_data('colloid-morghulis-system-hibernate-symbolic.svg', install_dir: '/usr/share/pixmaps/morghulis')
install_data('colloid-morghulis-system-lock-screen-symbolic.svg', install_dir: '/usr/share/pixmaps/morghulis')
install_data('colloid-morghulis-system-reboot-symbolic.svg', install_dir: '/usr/share/pixmaps/morghulis')
install_data('colloid-morghulis-system-shutdown-symbolic.svg', install_dir: '/usr/share/pixmaps/morghulis')
install_data('colloid-morghulis-system-suspend-symbolic.svg', install_dir: '/usr/share/pixmaps/morghulis')
