blueprints = custom_target(
    'blueprints',
    input: files(
        'MprisPlayer.blp',
        'NavBar.blp',
        'NotifPop.blp',
        'NotifWindow.blp',
        'OnScreenDisplay.blp',
        'PowerBox.blp',
        'QBluetooth.blp',
        'QBluetoothItem.blp',
        'QButton.blp',
        'QNetwork.blp',
        'QPowerProfiles.blp',
        'QuickMenu.blp',
        'Runner.blp',
        'RunnerButton.blp',
        'Settings.blp',
        'SliderBox.blp',
    ),
    output: '.',
    command: [
        find_program('blueprint-compiler'),
        'batch-compile',
        '@OUTPUT@',
        '@CURRENT_SOURCE_DIR@',
        '@INPUT@',
    ],
)