#!/usr/bin/env python3
"""Generate ensure_types(): force GType registration for every class, so
Blueprint templates can instantiate custom widgets by name.

Scans the given source roots for *.vala and emits one typeof(X).ensure() per
class. Replaces the hand-maintained init_types() in Main.vala.

Conditional-compilation: a file whose classes are only built under a meson
--define must carry a top-of-file marker

    // register-if: <define>

and its typeof() calls are wrapped in `#if <define> ... #endif` so the
generated file compiles whether or not that source is in the build.
"""

import re
import sys
from pathlib import Path

# Match public/internal/modifier-less classes (BatteryBox has no modifier).
# private classes are excluded: they are file-local helpers, never
# Blueprint-instantiated, and often nested (inaccessible by bare name).
CLASS_RE = re.compile(
    r'^\s*(?:(?:public|internal)\s+)?(?:sealed\s+|abstract\s+)?class\s+(\w+)\s*(?::\s*([\w.]+))?')
NS_RE = re.compile(r'^\s*namespace\s+(\w+)')
MARKER_RE = re.compile(r'//\s*register-if:\s*(\w+)')

# Only GObject-derived types can be registered with typeof().ensure(). Classes
# extending a non-GObject fundamental (e.g. GLib.Source) must be skipped.
NON_GOBJECT_BASES = {'GLib.Source', 'Source'}


def scan(path: Path):
    """Yield (guard_or_None, qualified_class_name) for one .vala file."""
    text = path.read_text(encoding='utf-8', errors='replace')
    guard = None
    ns = []
    depth = 0
    for line in text.splitlines():
        m = MARKER_RE.search(line)
        if m:
            guard = m.group(1)
        nm = NS_RE.match(line)
        if nm:
            ns.append(nm.group(1))
        cm = CLASS_RE.match(line)
        if cm:
            if cm.group(2) in NON_GOBJECT_BASES:
                continue
            name = '.'.join(ns + [cm.group(1)]) if ns else cm.group(1)
            yield guard, name


def main():
    out = Path(sys.argv[1])
    roots = [Path(r) for r in sys.argv[2:]]

    plain, guarded = [], {}
    for root in roots:
        for f in sorted(root.rglob('*.vala')):
            if '/vapi/' in f.as_posix() or f.name == 'ensure-types.vala':
                continue
            for guard, name in scan(f):
                if guard:
                    guarded.setdefault(guard, []).append(name)
                else:
                    plain.append(name)

    lines = ['// Generated by scripts/gen-ensure-types.py — do not edit.',
             'public void ensure_types() {']
    for name in plain:
        lines.append(f'    typeof({name}).ensure();')
    for guard in sorted(guarded):
        lines.append(f'#if {guard}')
        for name in guarded[guard]:
            lines.append(f'    typeof({name}).ensure();')
        lines.append('#endif')
    lines.append('}')
    lines.append('')

    content = '\n'.join(lines)
    # Rewrite only on change so build_always_stale doesn't trigger recompiles.
    if not out.exists() or out.read_text(encoding='utf-8') != content:
        out.write_text(content, encoding='utf-8')


if __name__ == '__main__':
    main()
