blps += files(
    'BatteryBox.blp',
    'MprisPlayer.blp',
    'PowerBox.blp',
    'QAudioBox.blp',
    'QAudioItem.blp',
    'QBluetooth.blp',
    'QBluetoothItem.blp',
    'QButton.blp',
    'QNetwork.blp',
    'QNetworkItem.blp',
    'QNotifications.blp',
    'QuickMenu.blp',
    'Settings.blp',
)