name: "Build and Release"
on:
  pull_request:
  push:
    tags:
      - "v*"
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v15
      with:
        name: nixarkye03
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Extract tag version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    - run: nix build .#fhs
    - run: nix flake check
    - uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "result/bin/morghulis-${{ steps.get_version.outputs.VERSION }}"
        bodyFile: "CHANGELOG.md"
